-- Tunisian tax/social settings for payroll calculation
INSERT INTO company_settings (setting_key, setting_value, description) VALUES
('cnss_rate', '11.26', 'CNSS employee contribution rate (%)'),
('cnss_employer_rate', '16.57', 'CNSS employer contribution rate (%)'),
('cnss_ceiling', '5173.085', 'CNSS monthly ceiling (plafond) in DT'),
('assurance_rate', '0.761', 'Assurance maladie rate (%)'),
('ir_tranche1', '5000', 'IR bracket 1 annual threshold in DT'),
('ir_rate1', '0', 'IR rate for bracket 1 (%)'),
('ir_tranche2', '20000', 'IR bracket 2 annual threshold in DT'),
('ir_rate2', '26', 'IR rate for bracket 2 (%)'),
('ir_tranche3', '30000', 'IR bracket 3 annual threshold in DT'),
('ir_rate3', '28', 'IR rate for bracket 3 (%)'),
('ir_tranche4', '50000', 'IR bracket 4 annual threshold in DT'),
('ir_rate4', '32', 'IR rate for bracket 4 (%)'),
('ir_tranche5', '999999', 'IR bracket 5 annual threshold in DT'),
('ir_rate5', '35', 'IR rate for bracket 5 (%)'),
('ir_abatement', '1080', 'IR annual abatement per salary in DT'),
('monthly_work_hours', '151.67', 'Standard monthly work hours in Tunisia'),
('currency', 'DT', 'Currency symbol');

-- Payroll tables
CREATE TABLE payrolls (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    month INT NOT NULL,
    year INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    total_gross DECIMAL(12,2) DEFAULT 0,
    total_deductions DECIMAL(12,2) DEFAULT 0,
    total_net DECIMAL(12,2) DEFAULT 0,
    employee_count INT DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_payroll_month_year (month, year)
);

CREATE TABLE payroll_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    payroll_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    base_salary DECIMAL(10,2) NOT NULL,
    prime_transport DECIMAL(10,2) DEFAULT 0,
    prime_performance DECIMAL(10,2) DEFAULT 0,
    prime_other DECIMAL(10,2) DEFAULT 0,
    overtime_hours DECIMAL(5,2) DEFAULT 0,
    overtime_amount DECIMAL(10,2) DEFAULT 0,
    total_gross DECIMAL(10,2) DEFAULT 0,
    cnss_deduction DECIMAL(10,2) DEFAULT 0,
    assurance_deduction DECIMAL(10,2) DEFAULT 0,
    ir_deduction DECIMAL(10,2) DEFAULT 0,
    late_deduction DECIMAL(10,2) DEFAULT 0,
    absence_deduction DECIMAL(10,2) DEFAULT 0,
    total_deductions DECIMAL(10,2) DEFAULT 0,
    net_salary DECIMAL(10,2) DEFAULT 0,
    days_worked INT DEFAULT 0,
    days_absent INT DEFAULT 0,
    late_minutes INT DEFAULT 0,
    total_overtime_minutes INT DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    paid_at DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_payroll_item_employee (payroll_id, employee_id),
    CONSTRAINT fk_payroll_item_payroll FOREIGN KEY (payroll_id) REFERENCES payrolls(id) ON DELETE CASCADE,
    CONSTRAINT fk_payroll_item_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);
