[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_mode = dio

lib_deps =
    miguelbalboa/MFRC522@^1.4.10
    adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
    adafruit/Adafruit GFX Library@^1.11.10
    adafruit/RTClib@^2.1.4
    adafruit/Adafruit Unified Sensor@^1.1.14
    fastled/FastLED@^3.9.10
    bblanchon/ArduinoJson@^7.0.4
    SD @^2.0.0
    WiFi @^2.0.0
    HTTPClient @^2.0.0
